config:
  ignore:
    - "README.md"
    - ".ticonfig.yml"
    - "**/Dockerfile*"
    - "Jenkinsfile"
    - "**/*.md"
    - "**/*.py"
    - "**/*.txt"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.xml"
    - "**/*.bazel"
    - "WORKSPACE"